# Generated by Django 5.2.11 on 2026-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_max', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hero',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='heroine',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
